In [1]:
#%pip install pyarrow

In [2]:
import pandas as pd

In [3]:
movies_imdb = pd.read_csv("title.akas.tsv", sep="\t", low_memory=False)

In [4]:
movies_imdb.columns

Index(['titleId', 'ordering', 'title', 'region', 'language', 'types',
       'attributes', 'isOriginalTitle'],
      dtype='object')

In [5]:
# get only Hindi movies and types imdbDisplay
movies_bollywood = movies_imdb[(movies_imdb['region'] == 'IN') & (movies_imdb['language'] == 'hi') & (movies_imdb['types'] == 'imdbDisplay')]

In [6]:
movies_bollywood.columns

Index(['titleId', 'ordering', 'title', 'region', 'language', 'types',
       'attributes', 'isOriginalTitle'],
      dtype='object')

In [7]:
movies_bollywood.describe()

          ordering  isOriginalTitle
count  34786.00000          34786.0
mean       9.87311              0.0
std       10.03691              0.0
min        2.00000              0.0
25%        4.00000              0.0
50%        7.00000              0.0
75%       11.00000              0.0
max      189.00000              0.0

In [8]:
#count number of unique movies by titleId
movies_bollywood['titleId'].nunique()

34488

In [9]:
movies_bollywood.to_parquet("bollywood_movies.parquet")

In [10]:
movies_bollywood.sample()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
1577921,tt0243061,10,Dragon Tales,IN,hi,imdbDisplay,\N,0

In [11]:
movies_bollywood.sample()['title']

44893713    Handa-kun
Name: title, dtype: object