In [2]:
%pip install pandas pyarrow

Collecting pandas
  Downloading pandas-2.3.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting pyarrow
  Downloading pyarrow-21.0.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (3.3 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mihirkurdekar/repos/bollywood-movie-picker/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/mihirkurdekar/repos/bollywood-movie-picker/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.2-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 6.5 MB/s eta 0:00:00a 0:00:01
Downloading pyarrow-21.0.0-cp310-cp310-macosx_12_0_arm64.whl (31.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.2/31.2 MB 6.6 MB/s eta 0:00:0000:0100:01
Downloading numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 7.8 MB/s eta 0:00:00a 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pyarrow, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.3.2 pyarrow-21.0.0 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd

In [8]:
movies_imdb = pd.read_csv("title.akas.tsv", sep="\t", low_memory=False)

In [9]:
movies_imdb.columns

Index(['titleId', 'ordering', 'title', 'region', 'language', 'types',
       'attributes', 'isOriginalTitle'],
      dtype='object')

In [10]:
# get only Hindi movies and types imdbDisplay
movies_bollywood = movies_imdb[(movies_imdb['language'] == 'hi') & (movies_imdb['types'] == 'imdbDisplay')]

In [11]:
movies_bollywood.columns

Index(['titleId', 'ordering', 'title', 'region', 'language', 'types',
       'attributes', 'isOriginalTitle'],
      dtype='object')

In [12]:

movies_bollywood.describe()

           ordering  isOriginalTitle
count  34788.000000          34788.0
mean       9.872858              0.0
std       10.036677              0.0
min        2.000000              0.0
25%        4.000000              0.0
50%        7.000000              0.0
75%       11.000000              0.0
max      189.000000              0.0

In [13]:
#count number of unique movies by titleId
movies_bollywood['titleId'].nunique()

34488

In [14]:
movies_bollywood.to_parquet("bollywood_movies.parquet")

In [30]:
movies_bollywood.sample()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
10589984,tt12453540,5,Shubhratri,IN,hi,imdbDisplay,\N,0

In [31]:
movies_bollywood.sample()['title']

1461723    Wadd: The Life & Times of John C. Holmes
Name: title, dtype: object

In [32]:
movies_bollywood.to_csv("movies_parquet.csv.gz", index=False, compression="gzip")

In [33]:
pd.read_csv("movies_parquet.csv.gz", compression="gzip").sample()

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
34297,tt9537082,6,Ranarangam,IN,hi,imdbDisplay,\N,0